### ISSUE TITLE
Uploads to Octoprint via watched folder are ignored

### ISSUE THREAD

**Issue by tewingflite** [OctoPrint/OctoPrint-Autoselect#3] opened 2017-04-03 08:14 UTC
When I dropped a gcode file via SMB connection to the watched folder I see Octoprint processed the file and placed it in the file list.  Autoselect did not pick up this file and begin printing.

**Comment by foosel** [comment] 2017-04-03 09:19
This is somewhat a duplicate of foosel/OctoPrint#1092. Reason is that the event the plugin depends on is the file upload event, which gets not triggered for the watched folder (not an actual upload).

Will solve this once the additional events mentioned in the linked ticket are available.

**Comment by foosel** [comment] 2017-04-03 09:19
See also #1

**Comment by foosel** [comment] 2017-05-16 09:37
Solved in 0.2.0, will start working with OctoPrint 1.3.3 (which introduces the required new events). Already works with 1.3.3rc1.

**Closed as completed by foosel** 2017-05-16 09:37 UTC
